export const COLLEGE_CREATE_REQUEST = 'COLLEGE_CREATE_REQUEST';
export const COLLEGE_CREATE_SUCCESS = 'COLLEGE_CREATE_SUCCESS';
export const COLLEGE_CREATE_FAIL = 'COLLEGE_CREATE_FAIL';
export const COLLEGE_CREATE_RESET = 'COLLEGE_CREATE_RESET';

export const COLLEGE_LIST_REQUEST = 'COLLEGE_LIST_REQUEST';
export const COLLEGE_LIST_SUCCESS = 'COLLEGE_LIST_SUCCESS';
export const COLLEGE_LIST_FAIL = 'COLLEGE_LIST_FAIL';
export const COLLEGE_LIST_RESET = 'COLLEGE_LIST_RESET';
