export const COLLEGE_CREATE_REQUEST = 'COLLEGE_CREATE_REQUEST';
export const COLLEGE_CREATE_SUCCESS = 'COLLEGE_CREATE_SUCCESS';
export const COLLEGE_CREATE_FAIL = 'COLLEGE_CREATE_FAIL';
export const COLLEGE_CREATE_RESET = 'COLLEGE_CREATE_RESET';

export const COLLEGE_LIST_REQUEST = 'COLLEGE_LIST_REQUEST';
export const COLLEGE_LIST_SUCCESS = 'COLLEGE_LIST_SUCCESS';
export const COLLEGE_LIST_FAIL = 'COLLEGE_LIST_FAIL';
export const COLLEGE_LIST_RESET = 'COLLEGE_LIST_RESET';

export const COLLEGE_DETAILS_REQUEST = 'COLLEGE_DETAILS_REQUEST';
export const COLLEGE_DETAILS_SUCCESS = 'COLLEGE_DETAILS_SUCCESS';
export const COLLEGE_DETAILS_FAIL = 'COLLEGE_DETAILS_FAIL';
export const COLLEGE_DETAILS_RESET = 'COLLEGE_DETAILS_RESET';

export const COLLEGE_DELETE_REQUEST = 'COLLEGE_DELETE_REQUEST';
export const COLLEGE_DELETE_SUCCESS = 'COLLEGE_DELETE_SUCCESS';
export const COLLEGE_DELETE_FAIL = 'COLLEGE_DELETE_FAIL';
export const COLLEGE_DELETE_RESET = 'COLLEGE_DELETE_RESET';

export const COLLEGE_UPDATE_REQUEST = 'COLLEGE_UPDATE_REQUEST';
export const COLLEGE_UPDATE_SUCCESS = 'COLLEGE_UPDATE_SUCCESS';
export const COLLEGE_UPDATE_FAIL = 'COLLEGE_UPDATE_FAIL';
export const COLLEGE_UPDATE_RESET = 'COLLEGE_UPDATE_RESET';
