export const PLANS_LIST_REQUEST = 'PLANS_LIST_REQUEST';
export const PLANS_LIST_SUCCESS = 'PLANS_LIST_SUCCESS';
export const PLANS_LIST_FAIL = 'PLANS_LIST_FAIL';
export const PLANS_LIST_RESET = 'PLANS_LIST_RESET';
