export const GET_USER_REVIEWS_REQUEST = 'GET_USER_REVIEWS_REQUEST';
export const GET_USER_REVIEWS_SUCCESS = 'GET_USER_REVIEWS_SUCCESS';
export const GET_USER_REVIEWS_FAIL = 'GET_USER_REVIEWS_FAIL';
export const GET_USER_REVIEWS_RESET = 'GET_USER_REVIEWS_RESET';
