export const REVIEWS_DETAILS_REQUEST = 'REVIEWS_DETAILS_REQUEST';
export const REVIEWS_DETAILS_SUCCESS = 'REVIEWS_DETAILS_SUCCESS';
export const REVIEWS_DETAILS_FAIL = 'REVIEWS_DETAILS_FAIL';
export const REVIEWS_DETAILS_RESET = 'REVIEWS_DETAILS_RESET';
